/* ===== SkillPrep — Lean Six Sigma & Sustainability (LinkedIn Learning) =====
   Mock test: 15 questions. p=part, q=question, o=options, a=index of correct (0=A), w=explanation
   Answer key verified against graded LinkedIn quiz screenshots where available. */
const LEAN_QUESTIONS = [
{p:"Process Improvement",q:"Your team project is consistently running late. How can the 5-Whys technique be applied to this situation?",o:["Identify the symptoms of the delays and address each issue individually as they arise","Ask why the project is running late multiple times until pinpointing poor initial planning as the root cause","Increase the number of team meetings to gather additional insights on project timelines","Focus on the latest symptom, such as missed deadlines, and find immediate remedies"],a:1,w:"5-Whys drills down through successive 'why' questions to the root cause instead of treating symptoms."},
{p:"Process Improvement",q:"Why is it important to align process improvements with organizational objectives?",o:["Focus on team-specific benefits alone suffices for motivation, making organizational alignment irrelevant.","Aligning process improvements with organizational objectives ensures that changes contribute to the wider goals and enhance overall effectiveness.","Organizational objectives are constantly changing, so aligning improvements with them can cause confusion.","Aligning objectives introduces unnecessary bureaucracy and slows down the implementation process."],a:1,w:"Improvements that ladder up to organizational goals actually move the business forward."},
{p:"Process Improvement",q:"You are reviewing your team's ongoing project. How should you involve stakeholders in the planning process to improve overall outcomes?",o:["Limit stakeholder involvement to technical aspects to maintain focus.","Include stakeholders primarily for final approval to ensure alignment.","Engage stakeholders early to surface valuable information and foster ownership.","Consult stakeholders only after initial planning to avoid divergent opinions."],a:2,w:"Early engagement uncovers insights and builds buy-in — approval-only involvement comes too late."},
{p:"Process Improvement",q:"What is the primary benefit of identifying value-added activities in a business process?",o:["It guarantees immediate cost savings and increased profits for the organization.","It helps in focusing efforts on tasks that directly impact customer satisfaction and product quality.","It ensures that all staff members are fully occupied throughout the workday.","It allows for the elimination of all non-essential business activities across the company."],a:1,w:"Value-added analysis concentrates effort where it matters to the customer."},
{p:"Process Improvement",q:"You are leading a project to transition to new technology in your department. What should you prioritize to minimize downtime and ensure a smooth implementation?",o:["Focus on achieving quick results without detailed planning.","Introduce new technology without assessing current resource gaps.","Provide necessary training and resources for the team.","Postpone training to save time and resources for later stages."],a:2,w:"Trained, resourced teams adopt new technology with minimal disruption."},
{p:"Lean & Sustainability",q:"What is the first step in implementing a sustainability project?",o:["Develop a project charter.","Create a timeline for the project.","Conduct a stakeholder analysis.","Define the goal of the sustainability project."],a:3,w:"You can't plan, staff, or measure what you haven't defined — start with the goal."},
{p:"Lean & Sustainability",q:"Which of the following is not a core competency of Lean management?",o:["gemba","continuous improvement","visual management","energy savings"],a:3,w:"Gemba (go see), kaizen (continuous improvement), and visual management are Lean staples; energy savings is an outcome, not a core competency."},
{p:"Lean & Sustainability",q:"What are the three different contexts of sustainability?",o:["economic, environmental, long-term business results","technological, environmental, economic","cultural, economic, environmental","social, environmental, economic"],a:0,w:"Per the course's answer key: economic, environmental, and long-term business results. (Note: the classic 'triple bottom line' is people/planet/profit — but this quiz expects the course framing.)"},
{p:"Lean & Sustainability",q:"What is one key strategy for building strong stakeholder relationships to improve sustainability performance?",o:["Increase the number of stakeholders regardless of their interest or influence.","Focus solely on short-term financial gains to attract stakeholders.","Minimize stakeholder engagement to streamline decision-making processes.","Engage stakeholders through regular and transparent communication."],a:3,w:"Regular, transparent communication is the foundation of stakeholder trust."},
{p:"Lean & Sustainability",q:"What is the primary purpose of the PDCA cycle in business processes?",o:["to ensure employee satisfaction","to implement and monitor continuous improvements","to eliminate all forms of waste","to increase production speed"],a:1,w:"Plan-Do-Check-Act is the engine of continuous improvement."},
{p:"Lean & Sustainability",q:"Which statement best describes the primary goal of Lean Six Sigma?",o:["to sustain results by improving processes, reducing defects, and minimizing waste","to increase the number of employees in an organization","to maximize the production output regardless of defects","to focus solely on reducing costs without considering quality"],a:0,w:"Lean Six Sigma = better processes + fewer defects + less waste, sustained over time."},
{p:"Lean & Sustainability",q:"Which of the following is not one of the eight types of waste identified by the DOWNTIME acronym in Lean methodology?",o:["Waiting","Overproduction","Defects","Innovation"],a:3,w:"DOWNTIME = Defects, Overproduction, Waiting, Non-utilized talent, Transportation, Inventory, Motion, Extra-processing. Innovation is not waste."},
{p:"Lean & Sustainability",q:"Which statement best describes the interconnection between health, commerce, business, industry, government, and education in the context of global sustainability?",o:["Only health and education are interconnected, with little influence from commerce, business, industry, and government.","They operate independently and have minimal impact on each other.","Government policies are the sole factor driving sustainability, with no significant input from health, commerce, business, industry, and education.","They are all closely linked and affect each other in various ways, influencing global sustainability efforts."],a:3,w:"Sustainability is a web — every sector influences and depends on the others."},
{p:"Lean & Sustainability",q:"Which of the following is not one of the 14 grand challenges for engineering?",o:["engineer better medicines","secure cyberspace","develop advanced AI for entertainment","provide access to clean water"],a:0,w:"Per the course's answer key, 'engineer better medicines' is the intended answer. (The NAE's real list does include better medicines — but this quiz follows the course's framing, so pick what the key expects.)"},
{p:"Lean & Sustainability",q:"What is the first step in creating a project charter for a sustainability initiative?",o:["Measure the current sustainability metrics.","Define the project's goals, scope, and key customer requirements.","Analyze the potential environmental impacts.","Develop a communication plan for stakeholders."],a:1,w:"A charter starts with goals, scope, and customer requirements — everything else follows."}
];
